---
version: '3.5'
services:

    db:
        platform: linux/arm64
        container_name: "db-dev"
        image: mariadb:10.3.38
        volumes:
            - ./data:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=${MARIADB_USER}
            - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        ports:
            - ${DBPORTS}
        env_file:
            - .env
        networks:
            - local

    redis:
        platform: linux/arm64
        container_name: "redis-dev"
        image: redis
        ports:
            - 6379:6379
        networks:
            - local

    rb:
        container_name: "${PROJECT_NAME}"
        build:
            context: .
            target: xdebug
        volumes:
            - ./:/www/
        env_file:
            - .env
        environment:
            - MIGRATION=true
        ports:
            - "1900:1900"
            - "1901:1901"
            - "1902:1902"
            - "1903:1903"
        networks:
            - local
        hostname: docker.host.name
        restart: always

networks:
    local:
        external:
            name: ${NETWORK}